# Generated by Django 5.0.1 on 2024-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('mother', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('registration', models.CharField(max_length=9)),
                ('year', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('clas', models.CharField(max_length=20)),
            ],
        ),
    ]
