# Generated by Django 5.0.1 on 2024-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedata',
            name='receipt',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='savedata/'),
        ),
        migrations.AddField(
            model_name='savedata',
            name='signature',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='savedata/'),
        ),
        migrations.AlterField(
            model_name='savedata',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
