# Generated by Django 5.0.1 on 2024-02-17 17:05

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_savedata_receipt_savedata_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedata',
            name='email',
            field=models.EmailField(default=service.models.get_default_email, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedata',
            name='receipt',
            field=models.FileField(default='None', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='savedata',
            name='signature',
            field=models.FileField(default='None', upload_to='signature/'),
        ),
    ]
