# Generated by Django 5.0.1 on 2024-02-19 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_savedata_email_alter_savedata_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedata',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
