# Generated by Django 5.0.1 on 2024-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_r_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='r_no',
        ),
    ]
