# Generated by Django 5.0.3 on 2024-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_store_delete_r_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedata',
            options={'ordering': ['-submit_time']},
        ),
        migrations.AddField(
            model_name='store',
            name='student_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='registration_no',
            field=models.CharField(default='null', max_length=9),
        ),
    ]
