# Generated by Django 5.0.3 on 2024-03-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_savedata_options_store_student_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='store',
            new_name='students_registration_no',
        ),
    ]
