# Generated by Django 5.0.3 on 2024-03-24 13:06

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_rename_store_students_registration_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='approved_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('mother', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('registration', models.CharField(max_length=9)),
                ('receipt', models.FileField(default='None', upload_to='approved_media')),
                ('signature', models.FileField(default='None', upload_to='approved_media')),
                ('year', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('clas', models.CharField(max_length=20)),
                ('email', models.EmailField(default=service.models.get_default_email, max_length=50)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='students_registration_no',
            name='registration_no',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='students_registration_no',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
    ]
