# Generated by Django 5.0.3 on 2024-03-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_approved_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approved_students',
            old_name='clas',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='branch',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='dob',
            new_name='e_year',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='end',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='father',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='mother',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='name',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='registration',
            new_name='r_no',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='receipt',
            new_name='receipt_file',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='email',
            new_name='s_email',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='signature',
            new_name='sign',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='start',
            new_name='t_clas',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='surname',
            new_name='t_end',
        ),
        migrations.RenameField(
            model_name='approved_students',
            old_name='year',
            new_name='t_from',
        ),
        migrations.RemoveField(
            model_name='approved_students',
            name='submit_time',
        ),
    ]
