# Generated by Django 4.2.11 on 2024-05-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_rename_clas_approved_students_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedata',
            name='period',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
